### ISSUE TITLE
Language models that create tools, and AI efficiency and democratization

### ISSUE THREAD

**Issue by alreadydone** [alreadydone/contents#3]
In response to https://leanprover-community.github.io/archive/stream/208328-IMO-grand-challenge/topic/Current.20status.3F.html#320982506

@**Mario Carneiro** I think models like the [Toolformer](https://twitter.com/timo_schick/status/1624058382142345216) that **offloads/outsources** some capabilities to external (symbolic) tools will drive down at least the inference cost, if not the training cost as well. [The paper](https://arxiv.org/abs/2302.04761) reports competitive zero-shot performance with much lower parameter count. (Langchain's [MRKL systems](https://arxiv.org/abs/2205.00445) are also mentioned by many people in connection with it.) [RETRO](https://www.deepmind.com/blog/improving-language-models-by-retrieving-from-trillions-of-tokens) performs well on **knowledge-intensive** tasks with much lower parameter count, by retrieving from a database rather than a toolbox. And there are architecture innovations like [RWKV-LM](https://github.com/BlinkDL/RWKV-LM) that are less resource-intensive than transformers but may prove to be as powerful (they just released an RNN with 14B parameters).

Next-generation models may be trained to not just use tools, but also **create tools** and organize them into a codebase (think of **long-term memory**, or **crystallized intelligence**), and they're gonna read books and papers and grow mathlib for us automatically (auto-formalization). Being able to execute programs and observe outputs serves as a strong form of **grounding** ([Yoav Goldberg](https://gist.github.com/cedrickchee/054956f6277430ae5a973c61e4a93073#natural-vs-curated-language-modeling), 5th paragraph), similar to formalization of mathematics. [Drori et al.'s PNAS paper](https://www.pnas.org/doi/abs/10.1073/pnas.2123433119) and [Program-aided Language Models](https://arxiv.org/abs/2211.10435) from CMU already do **program synthesis** in Python, but do not store the programs and build upon them; as we know, to prove a big theorem, it's often necessary to have lots of intermediate lemmas in place.

As the model **continually learns**, it might gradually **optimize** programs in its codebase (think of AlphaTensor), including other models it creates and stores there, so more efficient models could eventually emerge in the codebase and the original model could offload most of its capability to them, and we could just use the most efficient one. The original model probably need to be of **adaptive computation time** though, since otherwise offloading can't possibly save time even though it may improve accuracy. [Data center cooling](https://www.deepmind.com/blog/deepmind-ai-reduces-google-data-centre-cooling-bill-by-40), [neural architecture search](https://arxiv.org/abs/2302.14838), and [chip design](https://ai.googleblog.com/2020/04/chip-design-with-deep-reinforcement.html) are other places where a positive feedback loop for AI efficiency could be formed.

ChatGPT has shown that **reinforcement learning** can be a very effective way of aligning language models to our purposes, and a codebase has a naturally associated dependency graph, which could potentially help with **credit assignment**, so actions that wrote the most popular functions/theorems in the codebase/library could be rewarded. As a bonus, [PageRank is easy on a DAG](https://cstheory.stackexchange.com/questions/50507/pagerank-in-directed-acyclic-graphs-dag).

I've written down some thoughts in [this tweet thread](https://twitter.com/Junyan_Xu/status/1617789258898759680) a few weeks ago ~~but apparently I was talking into air~~ 😂  Are my ideas too crazy, or too well-known and already actively pursued in major labs @**Geoffrey Irving** @**Timothee Lacroix**? ~~Or maybe I was just shadow-banned by Twitter.~~ (Unfortunately it seems OpenAI's Lean paper authors have all left ...)

I think these ideas overlap with those of [memorizing transformers](https://arxiv.org/abs/2203.08913) from @**Yuhuai Tony Wu**, @**Christian Szegedy**, et al. which use non-differentiable memory as well, but memory access is via kNN lookup of vector embeddings. Since LMs are supposed to good at languages, I think it's natural to let them establish and follow **naming conventions** to name the new concepts they invented, and interact with their memory via tokens, but I don't have the experience to judge which approach is more practical.

As for **democratization of access**, I'm generally optimistic: I'm pretty impressed that I can now run Stable Diffusion (SD) to create 512x512 images [with just 4GB VRAM](https://github.com/cmdr2/stable-diffusion-ui) on my laptop. And it may not be difficult to adapt LMs to our particular purpose: for example, it now suffice to fine-tune only 3MB of the SD model's parameters on custom data, thanks to [LoRA](https://huggingface.co/blog/lora). **[Open Assistant](https://open-assistant.io/)** is now crowd-sourcing training data to create a ChatGPT clone, and this paradigm of distributed data generation combined with centralized training could be traced back to Leela Zero / Leela Chess Zero. It's worth noting that people are building [distributed training infrastructure](https://twitter.com/m_ryabinin/status/1625175933492641814) as well, but it may take time to mature.

**[Volunteer computing](https://en.wikipedia.org/wiki/Volunteer_computing)** has a long history and people have donated massive amounts of compute to projects like GIMPS (Mersenne prime search), or [Fishtest](https://github.com/glinscott/fishtest#readme), and through BOINC. So it's just a matter of **popularizing mathematics** to get more computing resources directed to mathlib. When AI is capable of creating new mathematics, it will draw even more volunteer resources: it's much more exciting to see long-standing conjectures being solved than seeing Elo rating keeps improving monotonically (pun intended). Considering how fast LMs can turn natural language into code and vice versa (already useful in reverse engineering), I think the **formal-informal gap** could be fairly small for machines.

Time is on our side. Conversational LMs will **revolutionize education**, and people around the world will get equal access to the most sophisticated mathematical ideas. Advanced mathematics will come out of brains of geniuses and ivory towers and reach more people than ever. (mathlib is already democratizing access to every detail for every proof and definition in it, which you don't normally get in textbooks, and LMs will be able to parse and summarize the Lean code and explain the big picture.) As automation progresses and people work less hours, they will have more spare time to devote to mathematics, among other means of entertainment. Gladly, Microsoft's CEO seems to [share the same vision](https://youtu.be/UNbyT7wPwk4?t=989):
> Do we need to learn math anymore? Why learn math?
Lemme tell you, I'm an electrical engineer who never understood the Maxwell's equations. So now I finally get, thanks to ChatGPT, a better understanding of it. So I think one of the things is we will all enjoy a lot more math because we will have that personalized tutor who will, in fact, be able to intervene at the crucial time when you're making a conceptual mistake and help you learn. So just imagine that, just Matt, what if there was a fantastic tutor teacher for every student learning math going forward, that is now possible.

Exciting times are ahead!

(Mandatory disclaimer: ChatGPT did not engage in the writing of this essay.)

**Comment by alreadydone** [comment]
New developments after I post the above on Zulip on Feb 14:

### LLaMA/Alpaca ecosystem

LLaMA model leak, [torrent](https://github.com/facebookresearch/llama/pull/73), [Hugging Face](https://github.com/facebookresearch/llama/pull/109), [hash](https://github.com/facebookresearch/llama/pull/87)
latest: [Facebook is going after LLaMA repos with DMCA's](https://news.ycombinator.com/item?id=35288415), https://github.com/github/dmca/blob/master/2023/03/2023-03-21-meta.md

LLaMA/Alpaca quantization, C++ implementation, CPU inference, https://github.com/ggerganov/llama.cpp, https://github.com/antimatter15/alpaca.cpp

Alpaca-LoRA, https://github.com/tloen/alpaca-lora, [4bit](https://github.com/johnsmith0031/alpaca_lora_4bit) (instruction fine-tuning)

Point Alpaca, https://alpaca.point.space/

### Open-source models

https://github.com/nichtdax/awesome-totally-open-chatgpt

**ChatGLM-6B** (Tsinghua), https://github.com/THUDM/ChatGLM-6B/blob/main/README_en.md

**ChatYuan** (ClueAI/元语智能), https://github.com/clue-ai/ChatYuan

**RWKV ecosystem** [Hacker News](https://news.ycombinator.com/item?id=35281992), [Twitter](https://twitter.com/BlinkDL_AI/status/1638555109373378560), [Reddit](https://www.reddit.com/r/MachineLearning/comments/11teywc/r_rwkv_14b_ctx8192_is_a_zeroshot/), [LoRA](https://github.com/Blealtan/RWKV-LM-LoRA) (weights: [7B](https://huggingface.co/BlueSunflower/RWKV-7B-alpaca-finetuned), [14B](https://huggingface.co/BlueSunflower/rwkv-4-14B-alpaca-finetune-lora-weights)), [TextSynth Server CPU inference](https://bellard.org/ts_server/), [Gradio demo](https://huggingface.co/spaces/BlinkDL/ChatRWKV-gradio), [blog post](https://johanwind.github.io/2023/03/23/rwkv_overview.html), [SpikeGPT](https://arxiv.org/abs/2302.13939)

### OpenAI

[ChatGPT release notes](https://help.openai.com/en/articles/6825453-chatgpt-release-notes)

**ChatGPT API** (90% cost reduction) https://openai.com/blog/introducing-chatgpt-and-whisper-apis

**GPT-4**, https://openai.com/research/gpt-4, https://openai.com/product/gpt-4, https://arxiv.org/abs/2303.08774
**GPTs are GPTs: An early look at the labor market impact potential of large language models**, https://openai.com/research/gpts-are-gpts
**Sparks of Artificial General Intelligence: Early experiments with GPT-4**, https://arxiv.org/abs/2303.12712

**OpenAI Evals**, https://github.com/openai/evals

**GitHub Copilot X**, https://github.blog/2023-03-22-github-copilot-x-the-ai-powered-developer-experience/

**Codex API discontinued**, replaced by ChatGPT (turbo) API https://news.ycombinator.com/item?id=35242069, https://github.com/reasoning-machines/pal/pull/14/files

### Other corporations

**Microsoft**: [Bing Chat](https://en.wikipedia.org/wiki/Microsoft_Bing#OpenAI_language_model) (search + browsing tool use, GPT-4 based, sort of ChatGPT plugin preview), [Bing Image Creator](https://blogs.microsoft.com/blog/2023/03/21/create-images-with-your-words-bing-image-creator-comes-to-the-new-bing/) (DALL-E based)

**Anthropic**: Claude

**Google**: PaLM API, Bard

**Baidu**: ERNIE Bot (文心一言) (Chinese language)

**Comment by alreadydone** [comment]
### Customization

https://twitter.com/johnjnay/status/1637843926840164353

-Supervised fine-tuning on your tasks
-Self-supervised learning (SSL) on your text

-RL w/ your reward model (RM)
-Filter high-temp outputs w/ RM
-Conditional SSL on RM-scored text

-Prompt w/ context
-Give it access to your tools
-Train (soft) parts of prompts

**RepoCoder: Repository-Level Code Completion Through Iterative Retrieval and Generation** (Microsoft / Wuhan), https://arxiv.org/abs/2303.12570

**OpenChatKit**, https://www.together.xyz/blog/openchatkit, featuring Customization recipes to fine-tune the model and Extensible retrieval system for live-updating answers.

**ChatGPT plugins**, https://openai.com/blog/chatgpt-plugins
Browsing, [Code interpreter](https://andrewmayneblog.wordpress.com/2023/03/23/chatgpt-code-interpreter-magic/), [Retrieval](https://github.com/openai/chatgpt-retrieval-plugin)
Third party: [Wolfram](https://writings.stephenwolfram.com/2023/03/chatgpt-gets-its-wolfram-superpowers/), etc.

**Copilot for Docs**, https://githubnext.com/projects/copilot-for-docs Compare https://github.com/context-labs/autodoc
**Copilot for Pull Requests**, https://githubnext.com/projects/copilot-for-pull-requests
**Copilot for Your Codebase** (WIP), https://githubnext.com/projects/copilot-view/
Copilot Chat, Voice, and Copilot for CLI

### Tool use

**Augmented Language Models: a Survey**, LeCun et al., https://arxiv.org/abs/2302.07842
[**Prompt Engineering: Augmented Language Models**](https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/#augmented-language-models), Lilian Weng
mentions TALM, https://arxiv.org/abs/2205.12255

**TaskMatrix.AI: Completing Tasks by Connecting Foundation Models with Millions of APIs** (Microsoft), https://arxiv.org/abs/2303.16434

**Visual ChatGPT: Talking, Drawing and Editing with Visual Foundation Models** (Microsoft), https://arxiv.org/abs/2303.04671
**HuggingGPT: Solving AI Tasks with ChatGPT and its Friends in HuggingFace** (Microsoft), https://arxiv.org/abs/2303.17580, https://github.com/microsoft/JARVIS

**Demonstrate-Search-Predict: Composing retrieval and language models for knowledge-intensive NLP** (Stanford), https://github.com/stanfordnlp/dsp

**Check Your Facts and Try Again: Improving Large Language Models with External Knowledge and Automated Feedback** (Microsoft/Columbia U), https://arxiv.org/abs/2302.12813

**ART: Automatic multi-step reasoning and tool-use for large language models** (UWash, Microsoft, UCI, Allen, Meta), https://arxiv.org/abs/2303.09014

**The surprising ease and effectiveness of AI in a loop**, Matt Webb, https://interconnected.org/home/2023/03/16/singularity

**A simple Python implementation of the ReAct pattern for LLMs**, Simon Willison, https://til.simonwillison.net/llms/python-react-pattern
See also **MM-ReAct: Prompting ChatGPT for Multimodal Reasoning and Action**, https://multimodal-react.github.io/

### Tool building (Coding)

**Planning with Large Language Models for Code Generation**, Tenenbaum and MIT-IBM Waston, https://arxiv.org/abs/2303.05510
Tenenbaum previously co-authored **DreamCoder: Growing generalizable, interpretable knowledge with wake-sleep Bayesian program learning**, https://arxiv.org/abs/2006.08381
See also **Self-planning Code Generation with Large Language Model** (PKU), https://arxiv.org/abs/2303.06689

**ViperGPT: Visual Inference via Python Execution for Reasoning** (Columbia U), https://viper.cs.columbia.edu/

**Reflexion: an autonomous agent with dynamic memory and self-reflection** (MIT / Northeastern), https://arxiv.org/abs/2303.11366, [blog post](https://nanothoughts.substack.com/p/reflecting-on-reflexion)

**Program of Thoughts Prompting: Disentangling Computation from Reasoning for Numerical Reasoning Tasks** (Waterloo/UCSB/Google, Nov 2022), https://github.com/wenhuchen/Program-of-Thoughts
compare **Program-aided Language Models**, https://arxiv.org/abs/2211.10435

### AI efficiency

**In AI, is bigger always better?**, Anil Ananthaswamy, https://www.nature.com/articles/d41586-023-00641-w

**CoLT5: Faster Long-Range Transformers with Conditional Computation** (Google), https://arxiv.org/abs/2303.09752

### Algorithm optimization

**EvoPrompting: Language Models for Code-Level Neural Architecture Search** (NYU/Google Brain), https://arxiv.org/abs/2302.14838

**Symbolic Discovery of Optimization Algorithms**, Quoc Le et al. (Google/UCLA), https://github.com/lucidrains/lion-pytorch, https://arxiv.org/abs/2302.06675

### Active learning

**Internet Explorer: Targeted Representation Learning on the Open Web**, Deepak Pathak et al. (CMU/Berkeley), https://internet-explorer-ssl.github.io/
Compare **Socially situated artificial intelligence enables learning from human interaction**, Li Fei-Fei et al., https://www.pnas.org/doi/10.1073/pnas.2115730119
See also **Rewarding Chatbots for Real-World Engagement with Millions of Users** (Chai Research), https://arxiv.org/abs/2303.06135

**Active Self-Supervised Learning: A Few Low-Cost Relationships Are All You Need**, LeCun et al., https://arxiv.org/abs/2303.15256

### Reinforcement learning

**Reward Design with Language Models** (Stanford/DeepMind), uses GPT3 API; proxy reward function is more akin to [Constitutional AI](https://twitter.com/AnthropicAI/status/1603791161419698181) than RLHF, https://arxiv.org/abs/2303.00001, [news](https://www.marktechpost.com/2023/03/08/researchers-from-stanford-and-deepmind-come-up-with-the-idea-of-using-large-language-models-llms-as-a-proxy-reward-function/)

**Vision-Language Models (Flamingo) as Success Detectors** (DeepMind), https://arxiv.org/abs/2303.07280

### Theorem proving

**Baldur: Whole-Proof Generation and Repair with Large Language Models**, First, Rabe, Ringer and Brun, https://arxiv.org/abs/2303.04910

**Magnushammer: A Transformer-based Approach to Premise Selection**, Albert Jiang, Szegedy, Yuhuai Wu et al., https://arxiv.org/abs/2303.04488

**ProofNet: Autoformalizing and Formally Proving Undergraduate-Level Mathematics** (new dataset), Zhangir Azerbayev, Ayers, Avigad et al. https://github.com/zhangir-azerbayev/ProofNet

### Future of Mathematics

**Some thoughts on automation and mathematical research**, Akshay Venkatesh, Nov 2021, https://www.math.ias.edu/~akshay/research/IASEssay.pdf
Fields Medal Symposium, Oct 2022 (pre-ChatGPT), http://www.fields.utoronto.ca/activities/22-23/fieldsmedalsym
Participants' impressions collected by Michael Harris https://siliconreckoner.substack.com/p/notes-from-the-2022-fields-medal

Terence Tao's [integration of ChatGPT](https://mathstodon.xyz/@tao/110049994510023907) into daily workflow, picked up by Chinese [news](https://www.163.com/dy/article/HVI64N5M0511DSSR.html) [outlets](https://www.jiqizhixin.com/articles/2023-03-06-3)
See also [**Would it be possible to create a tool to automatically diagram papers?**](https://terrytao.wordpress.com/2023/02/18/would-it-be-possible-to-create-a-tool-to-automatically-diagram-papers/)

**AI for Science: An Emerging Agenda** (Cambridge / Madison / Tübingen), https://arxiv.org/abs/2303.04217

### More

**Foundation Models for Decision Making: Problems, Methods, and Opportunities** (Google/Berkeley/MIT), https://arxiv.org/abs/2303.04129

**GPT-4: The Bitterer Lesson**, Alberto Romero, https://thealgorithmicbridge.substack.com/p/gpt-4-the-bitterer-lesson

**A Prompt Pattern Catalog to Enhance Prompt Engineering with ChatGPT** (Vanderbilt), https://arxiv.org/abs/2302.11382 and **ChatGPT Prompt Patterns for Improving Code Quality, Refactoring, Requirements Elicitation, and Software Design** (Vanderbilt), https://arxiv.org/abs/2303.07839

**Impact of Code Language Models on Automated Program Repair** (Alberta / Purdue), https://arxiv.org/abs/2302.05020

Program synthesis in chip design, https://hub.baai.ac.cn/view/24406 (Chinese)

**Comment by distbit0** [comment]
I did reply to your twitter thread btw https://twitter.com/0xDist/status/1631883008918835201.

Maybe I am also shadow-banned :sweat_smile:

I coincidentally both came across your twitter thread and this thread separately, but fully agree with both.

**Comment by alreadydone** [comment]
Thanks for your reply @distbit0 ! I wrote the post on Feb 14 before you replied :) I like the neuroscience articles you linked to but I'm not sure what inspirations to get from them ... I had written some responses to your tweets but too much is going on these days; when I get around to polish them a bit I'll post them here.

**Comment by alreadydone** [comment]
### LLM agent takeoff

https://github.com/Torantulino/Auto-GPT (>20k stars, implements code execution/improvement, inspired by HustleGPT)
https://github.com/reworkd/AgentGPT (web demo: https://agentgpt.reworkd.ai/)
https://github.com/yoheinakajima/babyagi (Yohei had been playing with LangChain and had the idea even before ChatGPT)
https://github.com/hwchase17/langchain (got [$10M investment](https://blog.langchain.dev/announcing-our-10m-seed-round-led-by-benchmark/), still a bit more stars than Auto-GPT at the moment): [Agents](https://python.langchain.com/en/latest/modules/agents/getting_started.html)
https://github.com/jtmuller5/The-HustleGPT-Challenge
https://github.com/pHaeusler/micro-agent
https://github.com/refcell/run-wild

[Lean 4 agent `sagredo`](https://leanprover.zulipchat.com/#narrow/stream/219941-Machine-Learning-for-Theorem-Proving/topic/sagredo/near/348135847) ([code](https://github.com/leanprover-community/mathlib4/compare/sagredo)), receives feedback from a proof assistant, but no web browsing etc. yet. See also https://github.com/leanprover-community/repl.

**Comment by distbit0** [comment]
Also some more: https://github.com/stars/distbit0/lists/agentic-ai

**Comment by nerzhul250** [comment]
Also add Jarvis to the list:
https://github.com/microsoft/JARVIS

**Comment by alreadydone** [comment]
> Also add Jarvis to the list:
[microsoft/JARVIS](https://github.com/microsoft/JARVIS)

Thanks! I classified HuggingGPT under the "tool use" section; it operates in four stages and doesn't have the recursive, unbounded nature of Auto-GPT-like agents.

**Comment by distbit0** [comment]
hey @alreadydone would you be up for a half hour call soon by any chance? Would be awesome to talk. https://cal.com/distbit/30min?duration=30

np if you are too busy. I should have more code+writing on these topics v soon which I will link to here anyway, if that is ok with you.
